Switch from inventory form file to directory for testinfra call
ansible-community/molecule pull request #2962
Opened 2020-11-10 14:54 UTC by amarao

#### PR Type
- Feature Pull Request

It should allow to use hostvars of non-managed hosts inside testinfra call (including delegation). See Issue #2961 for details.

2020-11-12 15:44 UTC, ssbarnea approved these changes

2020-11-12 16:48 UTC, ssbarnea commented
@amarao Does this break users that do not have a directory? Ansible allows both files or directory approach and if we implement support for folders while breaking the flat-inventory users we are in bit trouble, especially because the number of users using simple inventories is greater.

2020-11-12 17:07 UTC, cloudnull commented
:+1: to what @ssbarnea said, I'd like know this doesn't break existing use-cases.

2020-11-12 17:08 UTC, cloudnull requested changes
can we configure the provisioner with both file and directory support?

2020-11-13 10:23 UTC, amarao commented
@ssbarnea, When molecule constructs inventory, it writes `ansible_inventory.yaml`.  Current behavior: the path to this inventory fi is then passed to testinfra: (`self._config.provisioner.inventory_file`). Proposed behavior: write the same file, but pass the directory (`self._config.provisioner.inventory_directory,`) with `ansible_inventory.yaml`  inside as inventory.

As far as I understand ansible, there is no difference between inventory file and an inventory directory with the same file inside. Ansible  reads all yaml files from the inventory directory, so 'inventory file' is used in both cases. The difference is only if there are additional files. (This is the case with 'linked' hosts and group/hostvars directories). Group vars and Host vars are not affected, because host_group_vars plugin is searching them in both cases (file and directory).

If user used only constructed inventory (no links), then Ansible will read directory with a single file, no issues.
If user used links, than Ansible (under testinfra) start to see those links. (This is the reason for patch - I want to access data from `hosts` link).

The single issue I found is that tests may start to run against linked host, but it's easily solved:
```
verifier:
  name: testinfra
  options:
    force-ansible: true
    hosts: vms
```
(I have 'hypervisor' linked host and vms are provisioned and tested).

2020-11-15 12:04 UTC, merged