Refactor logging
ansible-community/molecule pull request #3000
Opened 2020-11-28 22:58 UTC by tadeboro

Molecule reinvented the logging for some reason and did not use the standard Python logging facilities as they are meant to be used. This PR brings some sanity to the logging part of the code.

#### PR Type

- Bugfix Pull Request

2020-11-29 10:49 UTC, ssbarnea requested changes
I see a regression: "Found config file" which is printed before does no longer happen with this patch.

2020-12-03 11:34 UTC, ssbarnea requested changes
Can you please fix the conflicts and ping me when this seams ready for review? (no known undesired side-effects). I will have to test it manually to assure we do not mess the logging even more with it but I need your confirmation first.

2020-12-03 12:31 UTC, tadeboro commented
I rebased the PR and tested it again locally. The only visible change of behavior from the master branch now should be the suppression of debug messages when running Molecule with no verbosity or debug flags.

2020-12-03 14:48 UTC, ssbarnea approved these changes

2020-12-03 14:51 UTC, merged