Fix pip documentation link
ansible-community/molecule pull request #3168
Opened 2021-06-25 15:45 UTC by tadeboro

Pip's documentation has been rearranged a bit, including the usage document that the Molecule documentation pointed to. This commit updated the link so that it now points to the quickstart document.

#### PR Type

- Docs Pull Request

2021-06-25 16:01 UTC, ssbarnea approved these changes

2021-06-25 16:02 UTC, ssbarnea requested changes
I think correct is `getting-started`? the one you proposed made me do a redirect.

2021-06-25 16:21 UTC, tadeboro commented
> I think correct is `getting-started`? the one you proposed made me do a redirect.

Yep, that would be the right one. I used grep on the `python -msphinx.ext.intersphinx https://pip.pypa.io/en/latest/objects.inv` output and failed to notice that the reference I selected is a redirect.

2021-06-28 10:53 UTC, ssbarnea approved these changes

2021-06-28 10:54 UTC, merged