Refactor use of lru_cache
ansible-community/molecule pull request #3180
Opened 2021-07-07 09:27 UTC by ssbarnea

Fixes: https://github.com/ansible-community/pytest-molecule/issues/95

2021-08-12 17:11 UTC, webknjaz commented on src/molecule/api.py
> +# @cache
why comment it out?

2021-08-12 17:12 UTC, webknjaz commented on src/molecule/compat.py
> +"""Compatibility layer for various Python versions."""
Could you plz `git mv src/molecule/{,_}compat.py`?

2021-08-31 16:33 UTC, tadeboro requested changes
The cache commit seems OK, but this PR also contains setuptools cleanup which should not be part of the current batch of changes.

2021-09-02 10:58 UTC, ssbarnea commented
> The cache commit seems OK, but this PR also contains setuptools cleanup which should not be part of the current batch of changes.

Sorted. Got combined by mistake while working on different changes.

2021-09-02 12:30 UTC, merged